name: Say hello Action

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola midudev!"
      - name: Dame la fecha
        run: date
      - run: ls -l
